// Human-readable case reports: a printable page (saved as PDF via the print dialog) and plain text.

import type { ScamScenario, Severity } from '../shared/types';
import type { Intruder } from '../shared/honeypot';

export interface CaseReport {
  caseId: string;
  generatedAt: Date;
  scamType: string;
  scammerContact: { name: string; number: string };
  decoyPersona: string;
  threat: { score: number; severity: Severity; signals: string[] } | null;
  intel: { upi: string[]; phones: string[]; urls: string[]; accounts: string[] };
  injectionAttempts: number;
  intruders: Intruder[]; // honeypot visitors (the scammer using the decoy login)
  transcript: { role: 'scammer' | 'persona'; text: string; at: number; classifiedAs?: ScamScenario }[];
}

const REPORT_TO = [
  ['National Cyber Crime Portal', 'cybercrime.gov.in · helpline 1930'],
  ['CERT-In (phishing links)', 'incident@cert-in.org.in'],
  ['Sanchar Saathi · Chakshu (fraud numbers)', 'sancharsaathi.gov.in'],
  ['NPCI (fraudulent UPI IDs)', 'npci.org.in'],
];

const INTEL_ROWS = (r: CaseReport) =>
  [
    ['UPI IDs', r.intel.upi],
    ['Phone numbers', r.intel.phones],
    ['Links', r.intel.urls],
    ['Bank accounts', r.intel.accounts],
  ] as const;

const fmtDate = (d: Date | number) =>
  new Date(d).toLocaleString([], { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
const fmtTime = (t: number) => new Date(t).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
const label = (s?: string) => (s ? s.replace(/_/g, ' ') : '');
const who = (r: CaseReport, role: 'scammer' | 'persona') =>
  role === 'scammer' ? `Scammer (${r.scammerContact.name})` : `${r.decoyPersona} (HawkGuard decoy)`;

// ─── Plain text ───────────────────────────────────────────────
export function reportText(r: CaseReport): string {
  const line = '─'.repeat(60);
  const out: string[] = [
    'HAWKGUARD THREAT REPORT',
    line,
    `Case ID:          ${r.caseId}`,
    `Generated:        ${fmtDate(r.generatedAt)}`,
    `Scam type:        ${r.scamType}`,
    `Scammer contact:  ${r.scammerContact.name}, ${r.scammerContact.number}`,
    `Decoy persona:    ${r.decoyPersona}`,
    r.threat ? `Risk score:       ${r.threat.score}/100 (${r.threat.severity.toUpperCase()})` : '',
    `Injection tries:  ${r.injectionAttempts} blocked`,
    '',
    'WHY IT WAS FLAGGED',
    line,
    ...(r.threat?.signals.length ? r.threat.signals.map((s) => `  • ${s}`) : ['  • No signals recorded']),
    '',
    'CAPTURED INTEL',
    line,
    ...INTEL_ROWS(r).map(([k, v]) => `  ${(k + ':').padEnd(16)}${v.length ? v.join(', ') : '—'}`),
    '',
    ...(r.intruders.length
      ? [
          'SCAMMER FINGERPRINT (HONEYPOT)',
          line,
          ...r.intruders.flatMap((v, i) => [
            `  Visitor ${i + 1}: ${v.device}, ${v.browser}${v.automated ? ' (automated tool)' : ''}`,
            `    IP address:   ${v.ip}`,
            `    Location:     ${v.geo.label}${v.geo.isp ? ` · ${v.geo.isp}` : ''}${v.geo.vpn ? ' · VPN/hosting IP' : ''}`,
            ...(v.geo.lat !== undefined && v.geo.lon !== undefined
              ? [`    Coordinates:  ≈ ${v.geo.lat}, ${v.geo.lon} (IP-based, city level)${v.geo.timezone ? ` · ${v.geo.timezone}` : ''}`]
              : []),
            ...(v.geo.asn ? [`    Network:      ${v.geo.asn}${v.geo.mobile ? ' (mobile)' : ''}`] : []),
            ...(v.language ? [`    Language:     ${v.language}`] : []),
            `    Active:       ${fmtTime(v.firstSeen)} – ${fmtTime(v.lastSeen)}${v.loggedIn ? ' · logged in to decoy' : ''}`,
            ...(v.credentialsTried.length
              ? [`    Credentials:  ${v.credentialsTried.map((c) => `${c.username} / ${c.password}`).join(', ')}`]
              : []),
            ...v.actions.map((a) => `    [${fmtTime(a.at)}] ${a.severity.toUpperCase().padEnd(8)} ${a.detail}`),
            '',
          ]),
          '',
        ]
      : []),
    'CONVERSATION TRANSCRIPT',
    line,
    ...r.transcript.flatMap((m) => [
      `[${fmtTime(m.at)}] ${who(r, m.role)}${m.classifiedAs ? `  · replying to ${label(m.classifiedAs)}` : ''}`,
      `  ${m.text}`,
      '',
    ]),
    'WHERE TO REPORT',
    line,
    ...REPORT_TO.map(([k, v]) => `  • ${k}: ${v}`),
    '',
    'Generated by HawkGuard. The scammer’s messages were never sent to the AI;',
    'persona replies were rewritten from pre-approved safe templates.',
  ];
  return out.filter((l, i) => l !== '' || out[i - 1] !== '').join('\n');
}

export function downloadText(r: CaseReport) {
  const blob = new Blob([reportText(r)], { type: 'text/plain;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `hawkguard-report-${r.caseId}.txt`;
  a.click();
  URL.revokeObjectURL(a.href);
}

// ─── Printable page → PDF ─────────────────────────────────────
const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function reportHtml(r: CaseReport): string {
  const sev = r.threat?.severity ?? 'unknown';
  const sevColor = sev === 'threat' ? '#d7263d' : sev === 'caution' ? '#c77700' : sev === 'safe' ? '#12805c' : '#5b6275';
  return `<!doctype html><html><head><meta charset="utf-8"><title>HawkGuard report ${esc(r.caseId)}</title>
<style>
  @page { size: A4; margin: 16mm 14mm; }
  * { box-sizing: border-box; }
  body { margin: 0; font: 11pt/1.5 -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #151823; }
  .mono { font-family: ui-monospace, 'SF Mono', Menlo, Consolas, monospace; }
  header { display: flex; justify-content: space-between; align-items: flex-end; padding-bottom: 12px; border-bottom: 3px solid #6d4dff; }
  .brand { font-size: 20pt; font-weight: 700; letter-spacing: -0.02em; }
  .brand small { display: block; font-size: 9.5pt; font-weight: 500; color: #5b6275; letter-spacing: 0; }
  .case { text-align: right; font-size: 9.5pt; color: #5b6275; }
  .case b { display: block; font-size: 12pt; color: #151823; }
  h2 { font-size: 10pt; text-transform: uppercase; letter-spacing: .08em; color: #5b6275; margin: 22px 0 8px; }
  .summary { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 24px; margin-top: 16px; }
  .summary div { display: flex; gap: 8px; }
  .summary dt { width: 120px; flex: 0 0 auto; color: #5b6275; }
  .summary dd { margin: 0; font-weight: 600; }
  .score { display: flex; align-items: center; gap: 14px; margin-top: 16px; padding: 12px 16px; border-radius: 10px; border: 1.5px solid ${sevColor}; background: ${sevColor}10; }
  .score-num { font-size: 26pt; font-weight: 800; color: ${sevColor}; line-height: 1; }
  .score-label { font-weight: 700; color: ${sevColor}; text-transform: uppercase; letter-spacing: .05em; }
  ul { margin: 0; padding-left: 18px; }
  table { width: 100%; border-collapse: collapse; }
  .intel td { padding: 6px 0; border-bottom: 1px solid #e6e8ef; vertical-align: top; }
  .intel td:first-child { width: 140px; color: #5b6275; }
  .chip { display: inline-block; margin: 0 6px 4px 0; padding: 2px 8px; border-radius: 6px; background: #eef1ff; border: 1px solid #cdd4ff; font-size: 9.5pt; }
  .none { color: #9aa0b0; }
  .msg { page-break-inside: avoid; display: grid; grid-template-columns: 52px 1fr; gap: 10px; padding: 8px 0; border-bottom: 1px solid #eef0f4; }
  .msg time { font-size: 9pt; color: #9aa0b0; padding-top: 2px; }
  .from { font-size: 9pt; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; }
  .from.scammer { color: #d7263d; }
  .from.persona { color: #5b3fe0; }
  .tag { font-weight: 500; color: #9aa0b0; text-transform: none; letter-spacing: 0; }
  .note { margin-top: 24px; padding: 10px 14px; border-radius: 8px; background: #f5f6fa; font-size: 9.5pt; color: #5b6275; }
  .intruder { page-break-inside: avoid; margin-bottom: 12px; padding: 10px 14px; border: 1.5px solid #d7263d; border-radius: 10px; }
  .intruder-head { font-weight: 700; margin-bottom: 4px; }
  .badge { font-size: 8.5pt; color: #fff; background: #d7263d; border-radius: 999px; padding: 1px 8px; margin-left: 6px; }
  .act { font-size: 10pt; } .act .mono { color: #9aa0b0; font-size: 9pt; margin-right: 4px; }
  .act.sev-critical { color: #d7263d; font-weight: 600; }
  .report-to td { padding: 4px 0; }
  .report-to td:first-child { width: 300px; padding-right: 16px; }
</style></head><body>
<header>
  <div class="brand">HawkGuard<small>Threat report · scam engagement</small></div>
  <div class="case">Case<b class="mono">${esc(r.caseId)}</b>${esc(fmtDate(r.generatedAt))}</div>
</header>

${r.threat ? `<div class="score"><div class="score-num">${r.threat.score}</div><div><div class="score-label">${esc(sev)}</div>Risk score out of 100</div></div>` : ''}

<dl class="summary">
  <div><dt>Scam type</dt><dd>${esc(r.scamType)}</dd></div>
  <div><dt>Decoy persona</dt><dd>${esc(r.decoyPersona)}</dd></div>
  <div><dt>Scammer contact</dt><dd>${esc(r.scammerContact.name)} · <span class="mono">${esc(r.scammerContact.number)}</span></dd></div>
  <div><dt>Injection attempts</dt><dd>${r.injectionAttempts} blocked</dd></div>
</dl>

<h2>Why it was flagged</h2>
<ul>${(r.threat?.signals.length ? r.threat.signals : ['No signals recorded']).map((s) => `<li>${esc(s)}</li>`).join('')}</ul>

<h2>Captured intel</h2>
<table class="intel">${INTEL_ROWS(r)
    .map(
      ([k, v]) =>
        `<tr><td>${k}</td><td>${v.length ? v.map((x) => `<span class="chip mono">${esc(x)}</span>`).join('') : '<span class="none">None captured</span>'}</td></tr>`
    )
    .join('')}</table>

${r.intruders.length ? `<h2>Scammer fingerprint · honeypot</h2>
${r.intruders
    .map(
      (v, i) => `<div class="intruder">
  <div class="intruder-head">Visitor ${i + 1} · ${esc(v.device)}, ${esc(v.browser)}${v.automated ? ' · automated tool' : ''}${v.loggedIn ? ' <span class="badge">logged in to decoy</span>' : ''}</div>
  <table class="intel">
    <tr><td>IP address</td><td class="mono">${esc(v.ip)}</td></tr>
    <tr><td>Location</td><td>${esc(v.geo.label)}${v.geo.isp ? ` · ${esc(v.geo.isp)}` : ''}${v.geo.vpn ? ' · <b>VPN / hosting IP</b>' : ''}</td></tr>
    ${v.geo.lat !== undefined && v.geo.lon !== undefined ? `<tr><td>Coordinates</td><td class="mono">≈ ${v.geo.lat}, ${v.geo.lon} <span class="none">(IP-based, city level${v.geo.timezone ? ` · ${esc(v.geo.timezone)}` : ''})</span></td></tr>` : ''}
    ${v.geo.asn ? `<tr><td>Network</td><td class="mono">${esc(v.geo.asn)}${v.geo.mobile ? ' (mobile)' : ''}</td></tr>` : ''}
    ${v.language ? `<tr><td>Language</td><td>${esc(v.language)}</td></tr>` : ''}
    ${v.credentialsTried.length ? `<tr><td>Credentials tried</td><td>${v.credentialsTried.map((c) => `<span class="chip mono">${esc(c.username)} / ${esc(c.password)}</span>`).join('')}</td></tr>` : ''}
    <tr><td>Actions</td><td>${v.actions.map((a) => `<div class="act sev-${a.severity}"><span class="mono">${fmtTime(a.at)}</span> ${esc(a.detail)}</div>`).join('')}</td></tr>
  </table>
</div>`
    )
    .join('')}` : ''}

<h2>Conversation transcript</h2>
${r.transcript
    .map(
      (m) => `<div class="msg"><time class="mono">${fmtTime(m.at)}</time><div>
  <div class="from ${m.role}">${esc(who(r, m.role))}${m.classifiedAs ? ` <span class="tag">· replying to ${esc(label(m.classifiedAs))}</span>` : ''}</div>
  <div>${esc(m.text)}</div></div></div>`
    )
    .join('')}

<h2>Where to report</h2>
<table class="report-to">${REPORT_TO.map(([k, v]) => `<tr><td>${k}</td><td class="mono">${v}</td></tr>`).join('')}</table>

<div class="note">Generated by HawkGuard. The scammer's messages were never sent to the AI — persona replies were rewritten from pre-approved safe templates, and no real personal data was shared.</div>
</body></html>`;
}

// Print just the report through a hidden iframe; the print dialog's "Save as PDF" produces the file
export function printAsPdf(r: CaseReport) {
  const frame = document.createElement('iframe');
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;';
  frame.srcdoc = reportHtml(r);
  frame.onload = () => {
    frame.contentWindow?.focus();
    frame.contentWindow?.print();
    setTimeout(() => frame.remove(), 60_000);
  };
  document.body.appendChild(frame);
}
